CREATE DATABASE eletrodomesticos_saep_db;
USE eletrodomesticos_saep_db;

CREATE TABLE USUARIO (
    USU_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USU_NOME VARCHAR(200),
    USU_EMAIL VARCHAR(200),
    USU_SENHA VARCHAR(200)
);

CREATE TABLE ELETRODOMESTICO (
    ELETRO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ELETRO_NOME VARCHAR(200),
    ELETRO_FORNECEDOR VARCHAR(200),
    ELETRO_CATEGORIA VARCHAR(200),
    ELETRO_POTENCIA VARCHAR(200),
    ELETRO_GARANTIA DATE,
    ELETRO_PRIORIDADE_REPOSICAO VARCHAR(200),
    ELETRO_CONSUMO VARCHAR(200),
    FK_USU_ID INTEGER 
);

CREATE TABLE LOGS (
    LOG_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LOG_DESCRICAO VARCHAR(200),
    LOG_DATA_HORA DATE
);

CREATE TABLE ESTOQUE (
    ESTQ_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ESTQ_QUANTIDADE INTEGER,
    FK_ELETRO_ID INTEGER 
);
 
ALTER TABLE ELETRODOMESTICO ADD CONSTRAINT FK_ELETRODOMESTICO_2
    FOREIGN KEY (FK_USU_ID)
    REFERENCES USUARIO (USU_ID);
 
ALTER TABLE ESTOQUE ADD CONSTRAINT FK_ESTOQUE_2
    FOREIGN KEY (FK_ELETRO_ID)
    REFERENCES ELETRODOMESTICO (ELETRO_ID);
    
INSERT INTO USUARIO (USU_NOME, USU_EMAIL, USU_SENHA) VALUES 
('Maria Silva', 'maria.silva@email.com', 'senha123cripto'),
('João Santos', 'joao.santos@empresa.com', 'minhasenha456'),
('Ana Oliveira', 'ana.oliveira@outlook.com', 'securepass789');

INSERT INTO ELETRODOMESTICO (ELETRO_NOME, ELETRO_FORNECEDOR, ELETRO_CATEGORIA, ELETRO_POTENCIA, ELETRO_GARANTIA, ELETRO_PRIORIDADE_REPOSICAO, ELETRO_CONSUMO, FK_USU_ID) VALUES 
('Geladeira Frost Free', 'Brastemp', 'Refrigeração', '150W', '2027-05-15', 'Alta', '120 kWh/mês', 1),
('Máquina de Lavar', 'Consul', 'Lavanderia', '500W', '2026-08-20', 'Média', '45 kWh/mês', 2),
('Micro-ondas 30L', 'Electrolux', 'Cozinha', '1100W', '2025-12-10', 'Baixa', '25 kWh/mês', 3);

INSERT INTO ESTOQUE (ESTQ_QUANTIDADE, FK_ELETRO_ID) VALUES 
(2, 1),  
(5, 2),  
(8, 3);